openapi: 3.0.0
info:
  title: pacserver API
  description: API to manage networks and proxy exceptions for dynamically generated PAC files
  version: 1.0.0

servers:
  - url: http://localhost:3000/api/v1
    description: local server

paths:
  /networks:
    get:
      summary: Returns a list of networks.
      responses:
        '200':
          description: A JSON array of networks in CIDR notation
          content:
            application/json:
              schema: 
                anyOf:
                  - $ref: '#/components/schemas/networksv4'
                  - $ref: '#/compoents/schemas/networksv6'
    patch:
      requestBody:
        content:
          application/json:
            schema:
              anyOf:
                - $ref: '#/components/schemas/networksv4'
                - $ref: '#/compoents/schemas/networksv6'
      responses:
        '200':
          description: Updated

components:
  schemas:
    networksv4:
      type: object
      properties:
        network:
          type: string
          format: ipv4
        proxystring:
          type: string
      required: 
        - network
    networksv6:
      type: object
      properties:
        network:
          type: string
          format: ipv6
        proxystring:
          type: string
      required: 
        - network
        - proxystring
    exceptions:
      type: object
      properties:
        domain:
          type: string
          format: ipv4
        proxystring:
          type: string
      required: 
        - domain
        - proxystring